[platformio]
default_envs = esp32-s2-bridge

[env:esp32-s2-bridge]
platform = espressif32
; WEMOS LOLIN ESP32-S2 Mini (ESP32-S2FN4R2, 4MB flash, 2MB PSRAM)
board = lolin_s2_mini
framework = arduino
monitor_speed = 115200
upload_speed = 460800
build_flags =
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D PSTATION_UART_RX_PIN=16
  -D PSTATION_UART_TX_PIN=17
  -D PSTATION_UART_BAUD=115200
